# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dm.proto',
  package='scanner',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08\x64m.proto\x12\x07scanner\"\x07\n\x05\x45mpty\"1\n\x0cZernikeModes\x12\r\n\x05modes\x18\x01 \x03(\x05\x12\x12\n\namplitudes\x18\x02 \x03(\x02\"\x1a\n\x07Timeout\x12\x0f\n\x07timeout\x18\x01 \x01(\x02\x32l\n\x02\x44M\x12<\n\x11SetDMZernikeModes\x12\x15.scanner.ZernikeModes\x1a\x0e.scanner.Empty\"\x00\x12(\n\x04Quit\x12\x0e.scanner.Empty\x1a\x0e.scanner.Empty\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='scanner.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=28,
)


_ZERNIKEMODES = _descriptor.Descriptor(
  name='ZernikeModes',
  full_name='scanner.ZernikeModes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modes', full_name='scanner.ZernikeModes.modes', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amplitudes', full_name='scanner.ZernikeModes.amplitudes', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=79,
)


_TIMEOUT = _descriptor.Descriptor(
  name='Timeout',
  full_name='scanner.Timeout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeout', full_name='scanner.Timeout.timeout', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ZernikeModes'] = _ZERNIKEMODES
DESCRIPTOR.message_types_by_name['Timeout'] = _TIMEOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'dm_pb2'
  # @@protoc_insertion_point(class_scope:scanner.Empty)
  })
_sym_db.RegisterMessage(Empty)

ZernikeModes = _reflection.GeneratedProtocolMessageType('ZernikeModes', (_message.Message,), {
  'DESCRIPTOR' : _ZERNIKEMODES,
  '__module__' : 'dm_pb2'
  # @@protoc_insertion_point(class_scope:scanner.ZernikeModes)
  })
_sym_db.RegisterMessage(ZernikeModes)

Timeout = _reflection.GeneratedProtocolMessageType('Timeout', (_message.Message,), {
  'DESCRIPTOR' : _TIMEOUT,
  '__module__' : 'dm_pb2'
  # @@protoc_insertion_point(class_scope:scanner.Timeout)
  })
_sym_db.RegisterMessage(Timeout)



_DM = _descriptor.ServiceDescriptor(
  name='DM',
  full_name='scanner.DM',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=109,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetDMZernikeModes',
    full_name='scanner.DM.SetDMZernikeModes',
    index=0,
    containing_service=None,
    input_type=_ZERNIKEMODES,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Quit',
    full_name='scanner.DM.Quit',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DM)

DESCRIPTOR.services_by_name['DM'] = _DM

# @@protoc_insertion_point(module_scope)
