# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from doptical.api import scanner_pb2 as doptical_dot_api_dot_scanner__pb2


class ScannerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartScan = channel.unary_unary(
                '/scanner.Scanner/StartScan',
                request_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                )
        self.StartLive = channel.unary_unary(
                '/scanner.Scanner/StartLive',
                request_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                )
        self.StopScan = channel.unary_unary(
                '/scanner.Scanner/StopScan',
                request_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                )
        self.Capture = channel.unary_unary(
                '/scanner.Scanner/Capture',
                request_serializer=doptical_dot_api_dot_scanner__pb2.Filename.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                )
        self.SetScanRange = channel.unary_unary(
                '/scanner.Scanner/SetScanRange',
                request_serializer=doptical_dot_api_dot_scanner__pb2.ScannerRange.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                )
        self.SetScanPixelRange = channel.unary_unary(
                '/scanner.Scanner/SetScanPixelRange',
                request_serializer=doptical_dot_api_dot_scanner__pb2.ScannerPixelRange.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                )
        self.GetScanRange = channel.unary_unary(
                '/scanner.Scanner/GetScanRange',
                request_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.ScannerRange.FromString,
                )
        self.GetScanImages = channel.unary_unary(
                '/scanner.Scanner/GetScanImages',
                request_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.Images.FromString,
                )
        self.GetScanImagesLength = channel.unary_unary(
                '/scanner.Scanner/GetScanImagesLength',
                request_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.ImagesLength.FromString,
                )
        self.GetScanImageBytes = channel.unary_unary(
                '/scanner.Scanner/GetScanImageBytes',
                request_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.Array.FromString,
                )
        self.SetPiezoPos = channel.unary_unary(
                '/scanner.Scanner/SetPiezoPos',
                request_serializer=doptical_dot_api_dot_scanner__pb2.PiezoPos.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                )
        self.SetSLMZernikeModes = channel.unary_unary(
                '/scanner.Scanner/SetSLMZernikeModes',
                request_serializer=doptical_dot_api_dot_scanner__pb2.ZernikeModes.SerializeToString,
                response_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                )


class ScannerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartLive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Capture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetScanRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetScanPixelRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanImagesLength(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanImageBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPiezoPos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSLMZernikeModes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScan,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            ),
            'StartLive': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLive,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            ),
            'StopScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StopScan,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            ),
            'Capture': grpc.unary_unary_rpc_method_handler(
                    servicer.Capture,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.Filename.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            ),
            'SetScanRange': grpc.unary_unary_rpc_method_handler(
                    servicer.SetScanRange,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.ScannerRange.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            ),
            'SetScanPixelRange': grpc.unary_unary_rpc_method_handler(
                    servicer.SetScanPixelRange,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.ScannerPixelRange.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            ),
            'GetScanRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanRange,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.ScannerRange.SerializeToString,
            ),
            'GetScanImages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanImages,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.Images.SerializeToString,
            ),
            'GetScanImagesLength': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanImagesLength,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.ImagesLength.SerializeToString,
            ),
            'GetScanImageBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanImageBytes,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.Empty.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.Array.SerializeToString,
            ),
            'SetPiezoPos': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPiezoPos,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.PiezoPos.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            ),
            'SetSLMZernikeModes': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSLMZernikeModes,
                    request_deserializer=doptical_dot_api_dot_scanner__pb2.ZernikeModes.FromString,
                    response_serializer=doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scanner.Scanner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scanner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/StartScan',
            doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartLive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/StartLive',
            doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/StopScan',
            doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Capture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/Capture',
            doptical_dot_api_dot_scanner__pb2.Filename.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetScanRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/SetScanRange',
            doptical_dot_api_dot_scanner__pb2.ScannerRange.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetScanPixelRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/SetScanPixelRange',
            doptical_dot_api_dot_scanner__pb2.ScannerPixelRange.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScanRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/GetScanRange',
            doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.ScannerRange.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScanImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/GetScanImages',
            doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.Images.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScanImagesLength(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/GetScanImagesLength',
            doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.ImagesLength.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScanImageBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/GetScanImageBytes',
            doptical_dot_api_dot_scanner__pb2.Empty.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.Array.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPiezoPos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/SetPiezoPos',
            doptical_dot_api_dot_scanner__pb2.PiezoPos.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSLMZernikeModes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scanner.Scanner/SetSLMZernikeModes',
            doptical_dot_api_dot_scanner__pb2.ZernikeModes.SerializeToString,
            doptical_dot_api_dot_scanner__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
